[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "heightmap_interpolation"
version = "1.1.0"
authors = [
  { name="Ricard Campos", email="ricard.campos@coronis.es" },
]
description = "Interpolation functions for heightmaps developed within the EMODnet Bathymetry (High Resolution Seabed Mapping) project."
readme = "Readme.md"
license = { file="LICENSE" }
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    "Natural Language :: English"
]
dependencies = [
    'matplotlib>=3.5.0b1',
    'numpy>=1.20.3',
    'haversine>=2.5.1',
    'scipy>=1.7.1',
    'netCDF4>=1.5.7',
    'fiona',
    'geopy>=2.2.0',
    'geopandas>=0.9.0',
    'opencv-python-headless>=4.5.3.56',    
    'numba>=0.54.1',
    'psutil>=5.8.0',
    'taichi',            
    'py_ams_point_interpolant'
]

[project.urls]
Homepage = "https://github.com/coronis-computing/heightmap_interpolation/"

[project.optional-dependencies]
docs = [        
    'sphinx',
    'sphinx-rtd-theme',
    'sphinx-autobuild'
]
experimental = [
    'opencv-contrib-python-headless>=4.5.3.56', # Shiftmap
    'exemplar-based-inpainting', # EBI
    'torch' # MLP
]
dev = [
    'ruff'
]

[tool.setuptools]
include-package-data=true

[tool.setuptools.packages.find]
where=["."]

[project.scripts]
interpolate_netcdf4 = "heightmap_interpolation.apps.interpolate_netcdf4:main"
interpolate_xyz = "heightmap_interpolation.apps.interpolate_xyz:main"

[tool.ruff]
line-length = 88
target-version = "py310"
select = ["E", "F", "W", "I"]
ignore = ["E203", "E266"]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"